[build]
    bin = "./tmp/server"
    cmd = "go build -o ./tmp/server ./cmd/server/main.go"
    exclude_dir = ["tmp"]
    exclude_regex = ["_test.go"]
    include_dir = ["cmd/server", "internal", "static", "views"]
